# Generated by Django 5.0.1 on 2024-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.IntegerField(default=1),
        ),
    ]
